name = "short-circuited"
license = "MIT"
licenselink = "https://github.com/phlagg/rewired/blob/main/LICENSE"
description = "A dark, minimal, terminal-inspired Hugo theme."
homepage = "https://github.com/phlagg/"
tags = [
    "blog",
    "portfolio",
    "dark",
    "minimal",
    "terminal",
    "dracula",
    "multilingual",
]
features = ["multilingual", "blog", "projects", "taxonomies", "responsive"]
min_version = "0.160.0"

[author]
name = "Rodrigo Iglesias"
homepage = "https://rigle.dev"
